################################################################################
#
# OpenThread Border Router
#
################################################################################

OPENTHREAD_VERSION = thread-reference-20230710
OPENTHREAD_SITE = $(call github,openthread,ot-br-posix,$(OPENTHREAD_VERSION))
OPENTHREAD_LICENSE = BSD-3-Clause
OPENTHREAD_LICENSE_FILES = LICENSE
OPENTHREAD_INSTALL_STAGING = NO
OPENTHREAD_INSTALL_TARGET = YES
OPENTHREAD_CONF_OPTS = -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
					   -DBUILD_SHARED_LIBS=OFF \
					   -DOTBR_BORDER_AGENT=ON \
					   -DBUILD_TESTING=OFF \
					   -DCMAKE_INSTALL_PREFIX=/usr \
					   -DOTBR_DBUS=ON \
					   -DOTBR_DNSSD_DISCOVERY_PROXY=ON \
					   -DOTBR_SRP_ADVERTISING_PROXY=ON \
					   -DOTBR_INFRA_IF_NAME=eth0 \
					   -DOTBR_MDNS=avahi \
					   -DOTBR_VERSION= \
					   -DOTBR_PACKAGE_VERSION=

# WEB_GUI
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_WEB_GUI),y)
OPENTHREAD_CONF_OPTS += -DOTBR_WEB=ON
endif

# BORDER_ROUTING
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_BORDER_ROUTING),y)
OPENTHREAD_CONF_OPTS += -DBACKBONE_ROUTING=ON
endif

# REST_SERVER
ifeq ($(BR2_PACAKGE_OPENTHREAD_BORDER_ROUTER_REST_SERVER),y)
OPENTHREAD_CONF_OPTS += -DOTBR_REST=ON
endif

# BACKBONE_ROUTER
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_BACKBONE_ROUTER),y)
OPENTHREAD_CONF_OPTS += -DBACKBONE_ROUTER=ON

# REFERENCE_DEVICE
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_REFERENCE_DEVICE),y)
OPENTHREAD_CONF_OPTS += -DOTBR_DUA_ROUTING=ON
endif
endif

# REFERENCE_DEVICE
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_REFERENCE_DEVICE),y)
OPENTHREAD_CONF_OPTS += -DOTBR_NO_AUTO_ATTACH=1 \
						-DOT_REFERENCE_DEVICE=ON \
						-DOT_DHCP6_CLIENT=ON \
						-DOT_DHCP6_SERVER=ON
endif

# NAT64
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_NAT64),y)
# NAT64_SERVICE_OPENTHREAD
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTER_NAT64_OPENTHREAD),y)
OPENTHREAD_CONF_OPTS += -DNAT64=ON \
						-DOT_POSIX_NAT64_CIDR="$(BR2_PACKAGE_OPENTHREAD_POSIX_NAT64_CID)"
endif

OPENTHREAD_CONF_OPTS += -DOTBR_DNS_UPSTREAM_QUERY=ON
endif

OPENTHREAD_SUPPORTS_IN_SOURCE_BUILD = NO
OPENTHREAD_DEPENDENCIES = avahi boost dbus iproute2 jsoncpp host-nodejs ncurses protobuf
OPENTHREAD_CMAKE_BACKEND = ninja

# Work around to checkout to the tag and run git submodule
define OPENTHREAD_EXTRACT_CMDS
rm -rf $(@D)
(git clone https://github.com/openthread/ot-br-posix $(@D) && \
 cd $(@D) && \
 git checkout $(OPENTHREAD_VERSION) && \
 git submodule update --init --recursive --depth 1)
touch $(@D)/.stamp_downloaded
endef

$(eval $(cmake-package))
